### ISSUE TITLE
ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers'

### ISSUE THREAD

**Issue by little-misfit** [haofanwang/ControlNet-for-Diffusers#30]
Thank you for your work. When I tried to reproduce your second part of image repair work, an error occurred. Your code included KarrasDiffusionSchedulers, but this class does not exist in the diffusers library. Is there a problem with my operation? How should I fix it?

Traceback (most recent call last):
  File "/root/autodl-tmp/ControlNet-for-Diffusers/test.py", line 2, in <module>
    from diffusers.utils import load_image
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/__init__.py", line 39, in <module>
    from .pipelines import (
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/pipelines/__init__.py", line 42, in <module>
    from .alt_diffusion import AltDiffusionImg2ImgPipeline, AltDiffusionPipeline
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/pipelines/alt_diffusion/__init__.py", line 33, in <module>
    from .pipeline_alt_diffusion import AltDiffusionPipeline
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py", line 36, in <module>
    from ..stable_diffusion.safety_checker import StableDiffusionSafetyChecker
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/__init__.py", line 46, in <module>
    from .pipeline_stable_diffusion_controlnet_inpaint import StableDiffusionControlNetInpaintPipeline
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet_inpaint.py", line 25, in <module>
    from ...schedulers import KarrasDiffusionSchedulers
**ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers'** (/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/schedulers/__init__.py)

**Comment by haofanwang** [comment]
Please install use a specific diffusers version for now. We will make our tutorial compatible to the latest official diffusers soon.

**Comment by little-misfit** [comment]
> Please install use a specific diffusers version for now. We will make our tutorial compatible to the latest official diffusers soon.
Thank you for your reply. Can you tell me how to install this special version of diffuser before you update the latest version of diffusers？

**Comment by little-misfit** [comment]
> Please install use a specific diffusers version for now. We will make our tutorial compatible to the latest official diffusers soon.

Thank you for your reply. Can you tell me how to install this special version of diffuser before you update the latest version of diffusers？
